import React, { useState } from 'react';
import { Sparkles, CheckSquare, Calendar, TrendingDown, DollarSign, Award } from 'lucide-react';

interface CarbonRecommendation {
  category: string;
  description: string;
  estimated_co2_savings_kg: number;
  estimated_cost_savings_usd: number;
}

interface ActionPlanData {
  title: string;
  score_impact: number;
  recommendations: CarbonRecommendation[];
}

interface ActionPlanProps {
  profileData: any;
  actionPlan: ActionPlanData | null;
  setActionPlan: (plan: ActionPlanData | null) => void;
  checkedTasks: boolean[];
  setCheckedTasks: (states: boolean[]) => void;
  onPlanComplete: (points: number) => void;
}

export const ActionPlan: React.FC<ActionPlanProps> = ({
  profileData,
  actionPlan,
  setActionPlan,
  checkedTasks,
  setCheckedTasks,
  onPlanComplete
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchActionPlan = async () => {
    if (!profileData) {
      setError("Please complete your Carbon Assessment (Calculator) first to generate a personalized plan.");
      return;
    }
    setLoading(true);
    setError(null);

    try {
      const API = import.meta.env.VITE_API_URL || "http://localhost:8000";
      const response = await fetch(`${API}/api/action-plan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(profileData)
      });

      if (!response.ok) {
        throw new Error("Failed to generate action plan. Verify your Vertex AI credentials.");
      }

      const plan: ActionPlanData = await response.json();
      setActionPlan(plan);
      setCheckedTasks(new Array(plan.recommendations.length).fill(false));
    } catch (err: any) {
      setError(err.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  const toggleTask = (index: number) => {
    const nextStates = [...checkedTasks];
    nextStates[index] = !nextStates[index];
    setCheckedTasks(nextStates);

    // If a task is checked, calculate and award incremental score points
    // Let's divide score_impact by the number of recommendations
    if (actionPlan) {
      const valuePerTask = actionPlan.score_impact / actionPlan.recommendations.length;
      if (nextStates[index]) {
        onPlanComplete(Math.round(valuePerTask));
      } else {
        onPlanComplete(-Math.round(valuePerTask));
      }
    }
  };

  // Calculate accumulated savings
  const totalCo2Saved = actionPlan?.recommendations.reduce((acc, rec, idx) => {
    return acc + (checkedTasks[idx] ? rec.estimated_co2_savings_kg : 0);
  }, 0) || 0;

  const totalCashSaved = actionPlan?.recommendations.reduce((acc, rec, idx) => {
    return acc + (checkedTasks[idx] ? rec.estimated_cost_savings_usd : 0);
  }, 0) || 0;

  const allCompleted = actionPlan && checkedTasks.length > 0 && checkedTasks.every(t => t === true);

  return (
    <div className="animate-slide-up" style={{ maxWidth: '720px', margin: '0 auto' }}>
      <div className="mb-32">
        <h1 style={{ fontSize: '2.5rem', fontWeight: 800 }}>Weekly AI Action Plan</h1>
        <p style={{ color: 'var(--text-secondary)' }}>Get custom-tailored tasks generated by Gemini to lower emissions.</p>
      </div>

      {error && (
        <div className="glass-panel" style={{ padding: '16px', borderLeft: '4px solid var(--color-danger)', borderRadius: 'var(--border-radius-md)', marginBottom: '24px', color: 'var(--text-primary)', fontSize: '0.9rem' }}>
          ⚠️ {error}
        </div>
      )}

      {!actionPlan ? (
        <div className="glass-panel" style={{ padding: '40px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '20px' }}>
          <div style={{ width: '64px', height: '64px', borderRadius: '50%', background: 'var(--color-glass-gradient)', border: '1px solid rgba(16, 185, 129, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-primary)' }}>
            <Sparkles size={28} />
          </div>
          <div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 700 }}>AI Goal Generator</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', maxWidth: '450px', marginTop: '6px' }}>
              Your Carbon Assessment profile will be evaluated by Gemini to draft 3 highly specific, reachable tasks that optimize your carbon rating.
            </p>
          </div>
          <button
            className="btn btn-primary"
            onClick={fetchActionPlan}
            disabled={loading || !profileData}
            style={{ width: 'fit-content' }}
          >
            {loading ? (
              <>
                <div className="loader-spinner" /> Drafting Plan...
              </>
            ) : (
              <>
                <Sparkles size={16} /> Generate AI Action Plan
              </>
            )}
          </button>
          {!profileData && (
            <span style={{ fontSize: '0.75rem', color: 'var(--color-danger)' }}>* Requires Carbon assessment profile. Please run the Calculator first.</span>
          )}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

          {/* Summary Panel */}
          <div className="glass-panel" style={{ padding: '24px', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px', textAlign: 'center' }}>
            <div>
              <div style={{ color: 'var(--color-emerald)', fontSize: '1.75rem', fontWeight: 800 }}>{totalCo2Saved.toFixed(1)} kg</div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500, marginTop: '2px' }}>Carbon CO₂ Saved</div>
            </div>

            <div>
              <div style={{ color: 'var(--color-sky)', fontSize: '1.75rem', fontWeight: 800 }}>${totalCashSaved.toFixed(2)}</div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500, marginTop: '2px' }}>Money Saved</div>
            </div>

            <div>
              <div style={{ color: 'var(--color-warning)', fontSize: '1.75rem', fontWeight: 800 }}>+{actionPlan.score_impact}</div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 500, marginTop: '2px' }}>Score Potential</div>
            </div>
          </div>

          {/* Checklist */}
          <div className="glass-panel" style={{ padding: '32px' }}>
            <div className="flex-between mb-24">
              <h2 style={{ fontSize: '1.25rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <CheckSquare size={20} color="var(--color-primary)" /> {actionPlan.title}
              </h2>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <Calendar size={12} /> Week of Jun 15, 2026
              </span>
            </div>

            <div className="checklist-container">
              {actionPlan.recommendations.map((rec, index) => (
                <div
                  key={index}
                  className={`checklist-item ${checkedTasks[index] ? 'checked' : ''}`}
                  onClick={() => toggleTask(index)}
                >
                  <div className="checklist-checkbox">
                    {checkedTasks[index] && <div style={{ width: '12px', height: '12px', background: 'currentColor', borderRadius: '2px' }} />}
                  </div>

                  <div className="checklist-content">
                    <span style={{
                      fontSize: '0.7rem',
                      fontWeight: 700,
                      textTransform: 'uppercase',
                      color: 'var(--color-primary)',
                      letterSpacing: '0.05em',
                      display: 'block',
                      marginBottom: '4px'
                    }}>
                      {rec.category}
                    </span>
                    <div className="checklist-title">{rec.description}</div>

                    <div className="checklist-metrics">
                      <span className="checklist-metric metric-co2">
                        <TrendingDown size={12} /> -{rec.estimated_co2_savings_kg} kg CO₂
                      </span>
                      <span className="checklist-metric metric-cost">
                        <DollarSign size={12} /> +${rec.estimated_cost_savings_usd}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {allCompleted && (
              <div className="glass-panel animate-fade-in" style={{ marginTop: '24px', padding: '16px', background: 'var(--color-glass-gradient)', border: '1px solid var(--color-primary)', borderRadius: 'var(--border-radius-md)', display: 'flex', alignItems: 'center', gap: '12px' }}>
                <Award color="var(--color-primary)" size={24} />
                <div>
                  <h4 style={{ fontWeight: 700, color: 'var(--color-primary)' }}>Weekly Champion Unlocked!</h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>You completed all weekly tasks. You earned the **Climate Champion** badge and boosted your score!</p>
                </div>
              </div>
            )}
          </div>

          <div style={{ textAlign: 'center' }}>
            <button
              className="btn btn-secondary"
              onClick={() => { setActionPlan(null); setCheckedTasks([]); }}
            >
              Reset and Draw New Goals
            </button>
          </div>

        </div>
      )}
    </div>
  );
};
